name: 02 - Workflow Events

on:
  push:
    branchs:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I have been triggered by a(n): ${{ github.event }} event."
