name: 04 - Using Actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: 04-using-actions/react-app 
        # com este aproach no campo defaults: podemos definicar campos padrões como o diretório padrão
        # assim evitamos repetição de código igual acontece abaixo


    # Abaixo vamos:
    #1. install dependencies of our react application
    #1. execute automated tests
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      #- name: Printing Folders
      #  run: ls
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        #run: npm ci -> se fizer isso direto dara erro pq irá rodar na raiz do projeto,
        #               por isso temos que entrar na pasta certa como está abaixo
        run: npm ci
        #working-directory: 04-using-actions/react-app
      - name: Run Unit Tests
        run: npm run test
        #working-directory: 04-using-actions/react-app