name: 04 - Using Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    #1. install dependencies of our react application
    #1. execute automated tests
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      #- name: Printing Folders
      #  run: ls
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        #run: npm ci -> se fizer isso direto dara erro pq irá rodar na raiz do projeto,
        #               por isso temos que entrar na pasta certa como está abaixo
        run: |
          cd 04-using-actions/react-app
          npm ci
        working-directory: 04-using-actions/react-app