name: 08 -  Variables
on: #workflow_dispatch
  push:
  workflow_dispatch: 

env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overriden by job'

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: 'I overrode thw workflow env'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env var"
          #Variáveis em letra maiuscula é uma convenção
          #Usar underline é mais interessante pois o hífen pode causar erros
        run: |
          echo "Step env step var com dollar-sign:  ${{env.STEP_VAR}}" 
          echo "Step env step var chamada igual no bash: $STEP_VAR "
          echo "Step env job var:  ${{env.JOB_VAR}}"
          echo "Ovewritten: ${{env.OVERWRITTEN}}"
      - name: Ovewrite job variable
        env:
          OVERWRITTEN: 'I overrode the job env'
        run: |
          echo "Step env var: ${{env.OVERWRITTEN}}"

          