name: 14 - Working with Artifacts
on: 
  workflow_dispatch:
    # inputs:
    #   use-cache:
    #     description: Whether to execute cache step
    #     type: boolean
    #     default: true
    #   node-version: 
    #     description: Node version
    #     type: choice
    #     options:
    #       - 18.x
    #       - 20.x
    #       - 21.x
    #     default: 20.x 
    

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 14-artifacts/react-app/node_modules #diretorio que queremos por no cache   
          key: deps-node-modules-${{hashFiles('14-artifacts/react-app/packge-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: unit tests
        run:  npm run test
      - name: Build code
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: 14-artifacts/react-app/build
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download build files
      uses: actions/download-artifact@v3
      with:
        name: app
        path: build #Para onde os artefatos irão
    - name: Show folder structure
      run: ls -R