name: 15 -  Working with Matrices
on: workflow_dispatch

jobs:
  backwards-compatibility:
    runs-on: ${{matrix.os}}-${{matrix.node-version}} #Desta maneira o github vai rodar em todas as combinações possíveis entre os e Node-version
    strategy:
      fail-fast: false # se for true, se um job falhar, todos os outros serão cancelados
      matrix:
        node-version: [ 18.x, 20.x, 21.x]  
        os: 
          - ubuntu-latest
          - windows-latest
        include: #essa chave permite adicionar combinações específicas que queremos
          - os: ubuntu-latest
            node-version: 16.x 
          - os: ubuntu-latest
            node-version: 23.x
            tag: experimental #Como esta combinação já existe, será adicionada essa tag a ela
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Perform  some tests
        run: |
          echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
          sleep 10
      - name: Upload test results
        run: echo "Uploading test results"